ucz/advert/urls.py
from django.urls import path
from .import views


app_name="advert"

urlpatterns = [


    path('phonesaless/<int:id>/',views.Phone_Sales, name='Phone_Sales'),
    path('phonerepairr/<int:id>/',views.Phone_Repair, name='Phone_Repair'),
    path('phonepartt/<int:id>/', views.Phone_Part, name='Phone_Part'),
    path('phoneaksesuarr/<int:id>/', views.Phone_Aksesuar, name='Phone_Aksesuar'),
    #---------------------DETAILS----------------------------------
    path('phonesales/<int:id>/', views.Phone_Sales_Details, name='Phone_Sales_Details'),
    path('phonerepair/<int:id>/', views.Phone_Repair_Details, name='Phone_Repair_Details'),
    path('phonepart/<int:id>/', views.Phone_Part_Details, name='Phone_Part_Details'),
    path('phoneaksesuar/<int:id>/',views.Phone_Aksesuar_Details, name='Phone_Aksesuar_Details'),


    
]

ucz/chat/urls.py
from django.urls import path
from .views import *

app_name="chat"

urlpatterns = [
    path('messages/', messages, name='messages'),
    path('messages/<int:receiver_id>/', messages, name='messages'),
]

ucz/hospital/urls.py
from django.urls import path
from .import views

app_name="hospital"
urlpatterns = [
    path('reapair',views.MobileRepair_Request,name="MobileRepair_Request"),
    path('reapairid/<int:id>',views.MobileRepair_Request_ID,name="MobileRepair_Request_ID"),
    path('garage/',views.Garage,name="Garage"),
    path('garageacceptancey /<int:id>',views.Garage_Acceptance_Yes,name="Garage_Acceptance_Yes"),
    path('garageacceptancen/<int:product>/<int:sender>/', views.Garage_Acceptance_No, name="Garage_Acceptance_No"),
    path('jobfinish/<int:product>/<int:receiver>/', views.Jobfinish_Business, name="Jobfinish_Business"),
    #--------------------------------
    path('jobfinishp/<int:product>/<int:id>/', views.Jobfinish_Personel, name="Jobfinish_Personel"),

   
]

ucz/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler404, handler500
from home.views import handle_not_found
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('user/', include("user.urls")),
    path('chat/', include("chat.urls")),
    path('advert/', include("advert.urls")),
    path('hospital/', include("hospital.urls")),
    # path('not-found/', handle_not_found, name='handle_not_found'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handle_not_found'

ucz/user/urls.py
from django.urls import path
from .import views

app_name="user"
urlpatterns = [
    path('login/',views.User_Login,name="Login"),
    path('register/',views.User_Register,name="Register"),
    path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:id>/',views.User_Info_Update,name="User_Info_Update"),


    path('logout/',views.logoutView,name="Logout"),

]

ucz/hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from advert .models import MobileRepair

# Create your models here.
class PhoneRepairRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_request' ,verbose_name="İsteği Atan")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_request',verbose_name="İsteği Alan")
    acceptance= models.BooleanField(verbose_name="İstek Onaylı Mı?",default=False)
    jobfinish= models.BooleanField(verbose_name="Ürün Teslim Edildi Mi? Telefon Sahibi Onay",default=False)
    jobfinish_business= models.BooleanField(verbose_name="Ürün Teslim Edildi Mi? İşletme Sahibi Onay",default=False)
    product= models.IntegerField(null=True,verbose_name="Hangi İlan")
    city=models.CharField(max_length=100,null=True,blank=False,verbose_name="İl")
    district=models.CharField(max_length=100,null=True,blank=False,verbose_name=" İlçe")
    phone_brand=models.CharField(max_length=250,null=True,blank=False,verbose_name="Telefon Markası")
    phone_model=models.CharField(max_length=250,null=True,blank=False,verbose_name="Telefon Modeli")
    created_date=models.DateTimeField(auto_now=True,verbose_name="Oluşturulma Tarihi")
#   jobfinish_created_date=models.DateTimeField(auto_now=False,verbose_name="Teslim Tarihi")

    def __str__(self):
        return  'sender={0}, acceptance={1}'.format(self.sender, self.acceptance)

ucz/hospital/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from .models import *
from user.models import BusinessStaff
from .views import *
from advert .models import MobileRepair
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import re
@login_required(login_url="user:Login")
def MobileRepair_Request(request):
    user = BusinessStaff.objects.filter(author_id=request.user.id, is_staff=True).first()
    if user:
        waits = PhoneRepairRequest.objects.filter(Q(acceptance=False, sender=request.user) | Q(acceptance=True, sender=request.user)).order_by('-created_date')
        if user.address:
            user_city = user.city

            # Türkçe karakterlere duyarlı olmayan düzenli ifade oluşturma fonksiyonu
            def create_regex_pattern(text):
                pattern = ''
                for char in text:
                    pattern += '[' + char.lower() + char.upper() + ']'
                return pattern

            # Kullanıcının şehir adındaki Türkçe karakterleri düzenli ifadelerle değiştirme
            user_city_pattern = create_regex_pattern(user_city)

            phone_repairs = MobileRepair.objects.filter(
                Q(is_active=True) & Q(jobfinish=False) & Q(acceptance=False) & 
                (Q(city__iregex=r'^{0}$'.format(user_city_pattern)) | Q(city__icontains=user.district))
            ).order_by('-created_date')
            
        else:
            phone_repairs = MobileRepair.objects.none()  # Empty queryset when address is not available
        jobfinish_ = PhoneRepairRequest.objects.filter(Q(sender=request.user) & Q(acceptance=True) & (Q(jobfinish=False) | Q(jobfinish=True))).order_by('-created_date')
        return render(request, 'hospital/hospital.html', {
            'user': user,
            'phone_repairs': phone_repairs,
            'waits': waits,
            'jobfinish_': jobfinish_
        })
    else:
        return redirect('home:index')


@login_required(login_url="user:Login")
def MobileRepair_Request_ID(request, id):

        
 
    try:
        phone_repair = get_object_or_404(MobileRepair, id=id)
        
        # Check if a PhoneRepairRequest with the same product already exists
        existing_request = PhoneRepairRequest.objects.filter(product=id).exists()
        if existing_request:
            # Handle the case when a PhoneRepairRequest with the same product already exists
            return redirect("hospital:MobileRepair_Request")
        
        kaydet = PhoneRepairRequest.objects.create(
            sender=request.user, 
            product=id, 
            receiver=phone_repair.author,
            phone_model=phone_repair.phone_model,
            phone_brand=phone_repair.phone_brand,
            city=phone_repair.city,
            district=phone_repair.district,
        )
        kaydet.save()
        return redirect('hospital:MobileRepair_Request')

    except:
        return render(request, "hospital/hospital.html")



@login_required(login_url="user:Login")
def Garage (request):
    user=BusinessStaff.objects.filter(author_id=request.user.id,is_staff=False)
    if user:
        waits=PhoneRepairRequest.objects.filter(Q(acceptance=False) & Q(receiver=request.user.id) | Q(acceptance=True)& Q(receiver=request.user.id))
        waits_with_sender_full_name = []
        for wait in waits:
            sender_full_name = wait.sender.get_full_name()  # Sender'ın full_name alanını al
            waits_with_sender_full_name.append({'request': wait, 'sender_full_name': sender_full_name})

        return render(request, 'hospital/garage.html', {
        'user_id': user,
        'waits':waits_with_sender_full_name

        })
   
    else:    # Eğer kullanıcı yoksa, aynı sayfayı döndürür
        if user:
        
            return redirect('user:Profil')
        else:
            return redirect('user:Profil')
    # return render(request,'hospital/garage.html')

@login_required(login_url="user:Login")
def Garage_Acceptance_Yes(request, id):
    repair_request = get_object_or_404(PhoneRepairRequest, product=id)
    repair_request.acceptance = True
    print(id,"Onayla")
    repair_request_2 = get_object_or_404(MobileRepair, id=id)
    repair_request_2.acceptance = True
    repair_request_2.save()
    
    repair_request.save()
    return redirect('hospital:Garage')

@login_required(login_url="user:Login")
def Garage_Acceptance_No(request,product,sender):
    # print(product,"Reddet",sender)
    repair_request = get_object_or_404(PhoneRepairRequest, product=product, sender=sender)
    repair_request.delete()
    return redirect('hospital:Garage')

@login_required(login_url="user:Login")
def Jobfinish_Business (request,product,receiver):
    jobfinish_business_ = get_object_or_404(PhoneRepairRequest, product=product,sender=request.user.id,receiver=receiver)
    jobfinish_business_.jobfinish_business = True
    jobfinish_business_.save()
    
    return redirect('hospital:MobileRepair_Request')

@login_required(login_url="user:Login")
def Jobfinish_Personel(request,product,id):
    jobfinish_personel_ = get_object_or_404(PhoneRepairRequest, product=product,receiver=request.user.id,sender=id)
    jobfinish_personel_.jobfinish = True
    jobfinish_personel_.save()
    return redirect('hospital:Garage')

ucz/templates/hospital/garage.html
{% extends 'base/base.html' %}

{% block body %}
<hr>

<!-- başlangıç-->
<div class="container-fluid ">
  <div class="col-md-12 mb-2 mt-5 ">
    <div class="card shadow border-0">
      <div class="card-header " style="background-color: #00DBDE;
      background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);
      ">
        <h5 class="card-title text-center">Telefon Tamir İstek Ekranı</h5>
      </div>
      <div class="card-body text-center" style="background-color: #00DBDE;
      background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);
      ">
        <div style="max-height:500px; overflow-y: scroll;">
          <table class="table table-striped table-hover thead-fixed">
            <thead style="background-color: #00DBDE;
            background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);
            " class="thead">
              <tr>
                <th scope="col">İstek Atan</th>
                <th scope="col">Marka-Model</th>
                <th scope="col">Tarih</th>
                <th scope="col">Onayla</th>
                <th scope="col">Reddet</th>
                <th scope="col">Tamir Edildi</th>
              </tr>
            </thead>
            <tbody>
              <!-- Örnek veriler -->
          {% if waits %}
          {% for wait in waits %}
              <tr>
                <td style="text-transform: uppercase;"><a href="{% url 'user:Profil'  wait.request.sender.id %}"  class="text-decoration-none text-white"> {{wait.sender_full_name}}</a></td>
                <td>{{wait.request.phone_brand }}-{{wait.request.phone_model}}</td>
                <td>{{wait.request.created_date }} </td>
                <td>
                  {% comment %} <button class="btn btn-success">Onayla</button> {% endcomment %}
                  {% if wait.request.acceptance == False %}
                  <a href="{% url 'hospital:Garage_Acceptance_Yes' wait.request.product %}"  class="btn btn-primary">ONAYLA</a>
                  {% else %}
                  <button type="button" class="btn btn-success" disabled>ONAYLANDI</button>
                  {% endif %}
                </td>
                <td>
                {% if wait.request.acceptance == False %}

                  {% comment %} <button class="btn btn-danger">Reddet</button> {% endcomment %}
                  <a href="{% url 'hospital:Garage_Acceptance_No' wait.request.product wait.request.sender.id%}"  class="btn btn-danger" >Reddet</a>
                  {% else %}
                  <button type="button" class="btn btn-danger" disabled>REDDET</button>
                  {% endif %}
                </td>
                {% if wait.request.jobfinish_business == False %}
                <td>
                  <button type="button" class="btn btn-primary" disabled>HENÜZ DEĞİL</button>
                {% else %}
                {% if wait.request.jobfinish == False %}
                <td>
                  <a href="{% url 'hospital:Jobfinish_Personel' wait.request.product wait.request.sender.id%}"  class="btn btn-primary">TESLİM AL</a>
                {% comment %} <button type="button" class="btn btn-primary" >Evet</button> {% endcomment %}
              </td>
              {% else %}
              <td style="background:#3FFF00;color:white">
              TESLİM ALINDI

              {% comment %} <a href=""  class="btn btn-success">{{ wait.request.product}}Teslim Alındı</a> {% endcomment %}
            </td>
              
              
              {% endif %}
                {% endif %}
       
              </tr>
              <tr>
                {% endfor %}
                {% else %}
              
                <tr> 
                  <td class="bg-danger text-white text-center ">TAMİR İSTEK LİSTESİ BOŞ</td>
                  
                </tr>
        
                {% endif %}
              <!-- Verileri buraya ekleyebilirsiniz -->



            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<!-- bitiş-->


</div>

{% endblock body %}

ucz/templates/hospital/hospital.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}

<hr>
<!--Ürün Açıklaması Ürün Özellikleri  Yorumlar BAŞLANGIÇ -->
<nav class="container-fluid mt-5">
  <div class="row">
    <div class="col-md-12">
      <div class="nav nav-tabs " id="nav-tab" role="tablist">
        <button class="nav-link active  text-white col-md-4 col-4"  id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true"  style="background: rgb(34,193,195);
      background: linear-gradient(0deg, rgba(34,193,195,1) 0%, rgba(253,187,45,1) 100%);">Telefon Tamir İlanları</button>

        <button class="nav-link col-md-4 col-4 text-white " id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false"
style="background-color: #4158D0;
background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);
">Telefon Tamir Onay Ekranı</button>



        <button class="nav-link  col-md-4 col-4 text-white    " id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-okey" type="button" role="tab" aria-controls="nav-profile" aria-selected="false"
style="background:background-color: #00DBDE;
background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);"


        >Tamir Edilmiş Telefonları Teslim Et</button>
      </div>
    </div>
  </div>
</nav>
<div class="tab-content mb-5" id="nav-tabContent">
  <!-- 1 Başlangıç -->
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
      <!-- BİRİNCİ TABLO başlangıç -->
    <div class="col-md-12 mb-2 ">
      <div class="card shadow border-0">

<div class="card-body ">
<div style="max-height: 400px; overflow-y: auto;">
  <table class="table table-striped  table-hover thead-fixed " style="background: rgb(34,193,195);
  background: linear-gradient(0deg, rgba(34,193,195,1) 0%, rgba(253,187,45,1) 100%);" >
    <thead style="position: sticky;top: 0" class="thead " >
     
      <tr style="background: rgb(34,193,195); 
      background: linear-gradient(0deg, rgba(34,193,195,1) 0%, rgba(253,187,45,1) 100%);" class="text-center" >
        <th>İl</th>
        <th>İlçe</th>
        <th>Marka-Model</th>
        <th>İlan Tarihi</th>
        <th>İlana Git</th>

      </tr>
    </thead>
    <tbody  class="text-center" >
      <!-- Örnek veriler -->
     {% if phone_repairs %}
      {% for phone_repair in phone_repairs %}

      <tr style="text-transform: uppercase;">

        <td>{{phone_repair.city}}</td>
        <td>{{phone_repair.district}}</td>
        <td>{{phone_repair.phone_brand}}-{{phone_repair.phone_model}}</td>
        <td >{{phone_repair.created_date}}</td>

        <td ><a href="{% url 'advert:Phone_Repair_Details' phone_repair.id %}"  class="btn btn-primary">Git</a></td>

      </tr>
      {% endfor %}
      
      {% else %}
      </tr>
      <tr>
      
      <td class="bg-danger text-white text-center ">Telefon Tamir İlan Listesi Boş</td>
    </tr>
      
      
      {% endif %}


      <!-- Verileri buraya ekleyebilirsiniz -->
    </tbody>

  </table>
</div>
</div>
</div>    
    </div>
<!-- BİRİNCİ TABLO BİTİŞ -->
              <!--<a href="#" class="btn btn-primary">Anasayafaya Git</a>--> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- 1 Bitiş -->

  <!-- 2 Başlangıç -->
  <div class="tab-pane fade mb-5" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
    <div class="container-fluid">
      <div class="row ">
        <div class="col-md-12 ">
          <div class="card ">
            <div class="card-body">
   <!-- 2 TABLO başlangıç -->
<div class="col-md-12 mb-2">
  <div class="card shadow border-0">

<div class="card-body">
<div style="max-height: 400px; overflow-y: auto;">
<table class="table table-striped  table-hover thead-fixed" style="background-color: #4158D0;
background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);
">
<thead style="position: sticky;top: 0;" class="thead" >
  <tr style="background-color: #4158D0;
  background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);
  "  class="text-center">
    <th>İl</th>
    <th>İlçe</th>
    <th>Marka-Model</th>
    <th>Kayıt Tarihi</th>
    <th>İstek Süreci</th>
  </tr>
</thead>
<tbody  class="text-center">
  <!-- Örnek veriler -->
  {% for wait in waits %}
  <tr style="text-transform: uppercase;">
    <td>{{wait.city}}</td>
    <td>{{wait.district}}</td>
    <td>{{wait.phone_brand}}-{{wait.phone_model}}</td>
    <td>{{wait.created_date}}</td>
    {% if wait.acceptance  %}
<td class="text-white h6" style="background:#3FFF00"><p>ONAYLANDI</p></td>
{% else %}
<td class=" text-white text-center" style="background: #FF0800"><p class="h6">BEKLENİYOR</p></td>

{% endif %}
  </tr>
  {% endfor %}

  <!-- Verileri buraya ekleyebilirsiniz -->
</tbody>

</table>
</div>
</div>
</div>    
</div>
<!-- 2 TABLO BİTİŞ -->

      </div>
    </div>
  </div>
</div>
</div>
</div>
  <!-- 2 Bitiş -->

  <!-- 3 Başlangıç -->
  <div class="tab-pane fade mb-5" id="nav-okey" role="tabpanel" aria-labelledby="nav-okey-tab" tabindex="0">
    <div class="container-fluid">
      <div class="row ">
        <div class="col-md-12 ">
          <div class="card ">
            <div class="card-body">
          

    <!-- 3 başlangıç -->
<div class="col-md-12 mb-5">
      <div class="card shadow border-0">

<div class="card-body">
<div style="max-height: 200px; overflow-y: auto;">
  <table class="table table-striped  table-hover thead-fixed" style="background:background-color: #00DBDE;
  background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);
  ">
    <thead style="position: sticky;top: 0" class="thead" >
      <tr style="background-color: #00DBDE;
      background-image: linear-gradient(270deg, #00DBDE 0%, #FC00FF 100%);
      "  class="text-center">
        <th>İl-İlçe</th>
        <th >Marka-Model</th>
        <th>İsim-Soyisim</th>
        <th>Teslim Et</th>
        <th>Sahip Onay</th>
      </tr>
    </thead>
    <tbody >
      <!-- Örnek veriler -->
      {% if jobfinish_ %}
      {% for jobfinish in jobfinish_ %}
      <tr  class="text-center" style="text-transform: uppercase;">
        <td>{{jobfinish.city}}-{{jobfinish.district}}</td>

        <td>{{jobfinish.phone_brand}}-{{jobfinish.phone_model}}</td>
        <td style="text-transform: uppercase;"><a href="{% url 'user:Profil' jobfinish.receiver.id %}"  class="text-decoration-none text-white"> {{ jobfinish.receiver.first_name }} {{ jobfinish.receiver.last_name }} </a></td>
        {% if jobfinish.jobfinish_business == False %}
        <td><a href="{% url 'hospital:Jobfinish_Business' jobfinish.product jobfinish.receiver.id %}"  class="btn  text-white" style="background:#C32BAC">ONAYLA</a></td>
        {% else %}
        <td class="text-white" style="background:#3CD500">ONAY İLETİLDİ</td>
       
        {% endif %}
        {% if jobfinish.jobfinish %}
        <td class="text-white text-center h6" style="background:#3FFF00">ONAYLANDI</td>
        {% else %}
        
        <td class="text-white text-center h6" style="background: #FF0800">BEKLENİYOR</td>
        
        {% endif %}
 
 
      </tr>

      {% endfor %}
      {% else %}
      <tr> 
        <td class="text-white text-center " style="background: #FF0800">TAMİR EDİLMİŞ TELEFON LİSTESİ BOŞ</td>
        
      </tr>

     
      {% endif %}
      <!-- Verileri buraya ekleyebilirsiniz -->
    </tbody>

  </table>
</div>
</div>
</div>
</div>
    <!-- 3 bitiş -->

      </div>
    </div>
  </div>
</div>
</div>
</div>
  <!-- 3 Bitiş -->
</div>

  
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('#inputDate').on('mousedown', function(e) {
      e.preventDefault();
    });
  });
  
  
</script>


{% endblock body %}