ucz/chat/urls.py
from django.urls import path
from .views import *

app_name="chat"

urlpatterns = [
    path('messages/', messages, name='messages'),
    path('messages/<int:receiver_id>/', messages, name='messages'),
]

ucz/home/urls.py
from django.urls import path
from .import views

app_name="home"
urlpatterns = [
    path('',views.index,name="index"),
    # path('about/',views.about,name="about"),
    # path('contact/',views.contact,name="contact"),
    # path('error/',views.error,name="error"),
    path('search', views.search_view, name='search'),
    path('contactform',views.Contact_Form, name='Contact_Form'),
    path('security',views.Security, name='Security'),
    path('conditions',views.Conditions, name='Conditions')

]

ucz/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler404, handler500
from home.views import handle_not_found
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('user/', include("user.urls")),
    path('chat/', include("chat.urls")),
    path('advert/', include("advert.urls")),
    path('hospital/', include("hospital.urls")),
    # path('not-found/', handle_not_found, name='handle_not_found'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handle_not_found'

ucz/user/urls.py
from django.urls import path
from .import views

app_name="user"
urlpatterns = [
    path('login/',views.User_Login,name="Login"),
    path('register/',views.User_Register,name="Register"),
    path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:id>/',views.User_Info_Update,name="User_Info_Update"),


    path('logout/',views.logoutView,name="Logout"),

]

ucz/templates/base/base.html
<!doctype html>
<html lang="tr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ucuzcebim.com</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body class="d-flex flex-column">
      <main class="flex-shrink-0">

        <nav class="navbar navbar-expand-lg bg-primary fixed-top bg-primary ">
            <div class="container ">
              <a class="navbar-brand text-white" href="{% url 'home:index' %}">ucuzcebim</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                  <li class="nav-item ">
                    <a class="nav-link active text-white" aria-current="page" href="{% url 'home:Contact_Form' %}">İletişim</a>
                  </li>
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="{% url 'user:Profil' request.user.id %}" style="text-transform: uppercase;">{{request.user}}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="{% url 'chat:messages' %}">Sohbet</a>
                  </li>
                  <li class="nav-item">
                    {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'chat:messages' %}">İlan Ver</a> {% endcomment %}
                    {% if user %}
                    <a class=" small text-decoration-none nav-link active text-white" aria-current="page"data-bs-toggle="modal" data-bs-target="#exampleModal3" data-bs-whatever="@getbootstrap" href="#!">İlan Ver</a>

                    {% else %} 
                    {% comment %} <h1 class="modal-title fs-5 " id="exampleModalLabel2">İlan Verebilmek İçin Formu Doldurunuz2</h1> {% endcomment %}
                    {% endif %}

                  </li>
                  {% else %}
                  {% endif %}
                  <!-- 
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  -->
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Hesap Bilgileri
                    </a>
                    <ul class="dropdown-menu">
                    {% if request.user.is_authenticated %}
                      <li><a class="dropdown-item" href="{% url 'user:Logout' %}">Çıkış Yap</a></li>
                       {% else %}
                       <li><a class="dropdown-item" href="{% url 'user:Login' %}">Giriş Yap</a></li>
                       <li><a class="dropdown-item" href="{% url 'user:Register' %}">Üye Ol</a></li>
                       {% endif %}
                       
                      <!-- 
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                      -->
                    </ul>
                  </li>
                  <!-- 
                  <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                  </li>
                   -->
                </ul>
                <form class="d-flex" method="GET" action="/search" role="search">
                  <div class="input-group">
                    <input class="form-control rounded-pill" name="query" type="search" placeholder="Telefoncu-Telefon Parçaları...." aria-label="Search" style="width: 370px;">
                    <button class="btn btn-dark rounded-pill" type="submit">Ara</button>
                  </div>
                </form>
                
                
                
              </div>
            </div>
          </nav>

          <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel3" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  {% if user_id %}
                  <h1 class="modal-title fs-5" id="exampleModalLabel2">ilan sayfası</h1>
                  {% else %} 
                  {% comment %} <h1 class="modal-title fs-5 " id="exampleModalLabel2">İlan Verebilmek İçin Formu Doldurunuz2</h1> {% endcomment %}
                  {% endif %}
                 
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                {% include 'adverts/advert_panel.html' %}
              </div>
            </div>
          </div>

    {% block body %}
    
    {% endblock %}




</main>
{% include 'base/footer.html' %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

ucz/templates/base/footer.html
<footer class="bg-dark py-4 mt-auto ">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; ucuzcebim.com 2023</div></div>
            <div class="col-auto">
                <a class="link-light small" href="{% url 'home:Security' %}">Gizlilik</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="{% url 'home:Conditions' %}">Şartlar</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="{% url 'home:Contact_Form' %}">İletişim</a>
            </div>
        </div>
    </div>
</footer>