ucz/chat/urls.py
from django.urls import path
from .views import *

app_name="chat"

urlpatterns = [
    path('messages/', messages, name='messages'),
    path('messages/<int:receiver_id>/', messages, name='messages'),
]

ucz/hospital/urls.py
from django.urls import path
from .import views

app_name="hospital"
urlpatterns = [
    path('reapair',views.MobileRepair_Request,name="MobileRepair_Request"),
    path('reapairid/<int:id>',views.MobileRepair_Request_ID,name="MobileRepair_Request_ID"),
    path('garage/',views.Garage,name="Garage"),
    path('garageacceptancey /<int:id>',views.Garage_Acceptance_Yes,name="Garage_Acceptance_Yes"),
    path('garageacceptancen/<int:product>/<int:sender>/', views.Garage_Acceptance_No, name="Garage_Acceptance_No"),
    path('jobfinish/<int:product>/<int:receiver>/', views.Jobfinish_Business, name="Jobfinish_Business"),
    #--------------------------------
    path('jobfinishp/<int:product>/<int:id>/', views.Jobfinish_Personel, name="Jobfinish_Personel"),

   
]

ucz/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler404, handler500
from home.views import handle_not_found
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('user/', include("user.urls")),
    path('chat/', include("chat.urls")),
    path('advert/', include("advert.urls")),
    path('hospital/', include("hospital.urls")),
    # path('not-found/', handle_not_found, name='handle_not_found'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handle_not_found'

ucz/user/urls.py
from django.urls import path
from .import views

app_name="user"
urlpatterns = [
    path('login/',views.User_Login,name="Login"),
    path('register/',views.User_Register,name="Register"),
    path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:id>/',views.User_Info_Update,name="User_Info_Update"),


    path('logout/',views.logoutView,name="Logout"),

]

ucz/templates/adverts_details/detail_message_modal.html
<div class="modal-body">
  <form  method="post" action="{% url 'chat:messages' user.id %}  "  enctype="multipart/form-data">
     {% csrf_token %}
        <!-- formFile -->
        <div class="row">
          <div class="col-md-12 mb-4">

            <div class="card mb-3" style="max-width: 540px;">
              <div class="row g-0">
                <div class="col-md-4">
                  {% if product.avatar %}
                  <img  class="img-fluid rounded-start" src="{{ product.avatar.url }}" />
              {% else %}
                  <p>Resim mevcut değil.</p>
              {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"> {{ product.phone_brand }}&nbsp;{{ product.phone_model}}&nbsp;{{ product.part_name }}&nbsp;{{ product.aksesuar_name }} </h5>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
        <!-- formFile -->



  <!-- message -->
  <input type="hidden" name="receiver" value="{{ user.id }}">
  <div class="form-group">
    <textarea name="content" class="form-control" placeholder="Mesajınız..." rows="3"></textarea>
  </div>
  <!-- message -->
  

  <div class="d-grid gap-1 d-md-flex justify-content-md-center">
    {% if request.user.is_authenticated %}
    <button type="submit" class="btn btn-info d-block mt-2 w-100">Mesajı Gönder</button>
    {% else %}
    <button type="button" disabled class="btn btn-info d-block w-100 mt-2">Mesajı Gönder</button>
    {% endif %}
    {% comment %}<button type="button" class="btn btn-danger d-block" data-bs-dismiss="modal">İptal</button>{% endcomment %}
  </div>
  </form>
</div>








  

ucz/templates/adverts_details/phone_aksesuar_details.html
{% extends 'base/base.html' %}

{% block body %}

  <div class="container mt-4">

<!-- content -->
<section class="py-5">
  <div class="container">
    <div class="row gx-5">
      <aside class="col-lg-6">
        <div class="border rounded-4 mb-3 d-flex justify-content-center bg-light shadow border-0">
          <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="{{ product.avatar.url }}">
            {% if product.avatar %}
            <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{ product.avatar.url }}" />
        {% else %}
            <p>Resim mevcut değil.</p>
        {% endif %}
          </a>
        </div>
      </aside>
      <main class="col-lg-6 ">
        <div class="ps-lg-3 bg-light shadow border-0">
          <h4 class="title text-dark pt-1 text-center">
            {{ product.aksesuar_name }}  <br />
          </h4>
          <hr>
          <div class="row ">
            <dt class="col-3">Fiyat:</dt>
            <dd class="col-9"><span class="h5 badge bg-danger bg-gradient rounded-pill">{{ product.price}}&nbsp;TL</span></dd>




            <dt class="col-3">İl:</dt>
            <dd class="col-9">{{product.city}}</dd>
            <dt class="col-3">İlçe:</dt>
            <dd class="col-9">{{product.district}}</dd>
            <dt class="col-3">Durumu:</dt>
            <dd class="col-9">{{product.situation}}</dd>


            <dt class="col-3">İlan Tarihi:</dt>
            <dd class="col-9">{{product.created_date|date:"d.m.Y"}}</dd>
            <dt class="col-3">Kategori:</dt>
            <dd class="col-3 badge bg-primary bg-gradient rounded-pill ">{{product.label}}</dd>
          </div>
          <hr>
          <div class="d-flex justify-content-center ">
            <div class="mr-3">
              <p class="mb-1 mt-4 h5"></p>
              <p class="small text-muted-info mb-0" style="text-transform: uppercase;">İlan Sahibi:</p>
            </div>
            <div class="px-3 mb-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted mb-0"><a class="small text-decoration-none" href="{% url 'user:Profil' product.author.id %}" style="text-transform: uppercase;">{{full_name}}</a></p>
            </div>
            {% if request.user.id != user.id%}
            <div class="px-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!" style="text-transform: uppercase;">Mesaj Gönder</a></p>
            </div>
            
            {% comment %} <div class="px-3 mb-2">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!">Favoriye Ekle</a></p>
            </div> {% endcomment %}
            {% endif %}
          </div>
        </div>
      </main>
    </div>
  </div>
</section>
<!-- content -->



<!-- detail message modal başlangıç-->
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start mt-3">
  <!--<a class="btn btn-outline-info btn-lg px-4" href="#!">Profili Düzenle</a>-->

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       {% if  request.user.is_authenticated %}
       <div class="alert alert-info  w-100 text-center" role="alert">
      <a  class="alert-link text-decoration-none"style="text-transform: uppercase;">{{full_name}}</a>
      </div>
       {% else %} 
       <h1 class="modal-title fs-5 " id="exampleModalLabel">
        <a href="{% url 'user:Login' %}" class="text-decoration-none">Mesajlaşmak için oturum açın...</a>
       </h1>
       {% endif %}
      
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

     </div>
     {% include 'adverts_details/detail_message_modal.html' %}

    <!-- modal mesaj başlangıç-->
    

<div class="modal-footer">
  {% comment %} <button type="submit" class="btn btn-primary">
    GİRİŞ YAP
  </button> {% endcomment %}

  {% comment %} <a href="{% url 'user:User_Info_Save'  %}" class="btn btn-warning d-block mt-1">Düzenle</a> {% endcomment %}


</div>
    <!-- modal mesaj bitiş-->
   </div>
 </div>
</div>

</div>
<!-- detail message modal bitiş-->



    <div class="row gx-4  ">
      <div class="col-lg-12 ">
        <div class="border rounded-2 px-3 py-2 bg-white shadow border-0">
          <!-- Pills navs -->
          <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
            <li class="nav-item d-flex" role="presentation">
              <a class="nav-link d-flex align-items-center " id="ex1-tab-1" data-mdb-toggle="pill" href="#ex1-pills-1" role="tab" aria-controls="ex1-pills-1" aria-selected="true">Ürün Açıklaması</a>
            </li>

          </ul>
          <!-- Pills navs -->
          <!-- Pills content -->
          <div class="tab-content" id="ex1-content">
            <div class="tab-pane fade show active" id="ex1-pills-1" role="tabpanel" aria-labelledby="ex1-tab-1">
              <p>
                {{product.comment}}
              </p>
            </div>

          </div>
          <!-- Pills content -->
        </div>
      </div>


<!-- Footer -->

<!-- Footer -->



  </div>

{% include 'home/product.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script>
    // Özel JavaScript kodları buraya eklenebilir
  </script>

  {% endblock body %}

ucz/templates/adverts_details/phone_part_details.html
{% extends 'base/base.html' %}

{% block body %}

  <div class="container mt-4">

<!-- content -->
<section class="py-5">
  <div class="container">
    <div class="row gx-5">
      <aside class="col-lg-6">
        <div class="border rounded-4 mb-3 d-flex justify-content-center bg-light shadow border-0">
          <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="{{ product.avatar.url }}">
            {% if product.avatar %}
            <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{ product.avatar.url }}" />
        {% else %}
            <p>Resim mevcut değil.</p>
        {% endif %}
          </a>
        </div>
      </aside>
      <main class="col-lg-6 ">
        <div class="ps-lg-3 bg-light shadow border-0">
          <h4 class="title text-dark pt-1 text-center">
            {{ product.part_name }}  <br />
          </h4>
          <hr>
          <div class="row ">
            <dt class="col-3">Fiyat:</dt>
            <dd class="col-9"><span class="h5 badge bg-danger bg-gradient rounded-pill">{{ product.price}}&nbsp;TL</span></dd>



            <dt class="col-3">Takas:</dt>
            <dd class="col-9">{{product.swap}}</dd>
            <dt class="col-3">İl:</dt>
            <dd class="col-9">{{product.city}}</dd>
            <dt class="col-3">İlçe:</dt>
            <dd class="col-9">{{product.district}}</dd>
            <dt class="col-3">Durumu:</dt>
            <dd class="col-9">{{product.situation}}</dd>
            <dt class="col-3">Garanti</dt>
            <dd class="col-9">{{product.garanti}}</dd>

            <dt class="col-3">İlan Tarihi:</dt>
            <dd class="col-9">{{product.created_date|date:"d.m.Y"}}</dd>
            <dt class="col-3">Kategori:</dt>
            <dd class="col-3 badge bg-primary bg-gradient rounded-pill ">{{product.label}}</dd>
          </div>
          <hr>
          <div class="d-flex justify-content-center">
            <div class="mr-3">
              <p class="mb-1 mt-4 h5"></p>
              <p class="small text-muted-info mb-0" style="text-transform: uppercase;">İlan Sahibi:</p>
            </div>
            <div class="px-3 mb-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted mb-0"><a class="small text-decoration-none" href="{% url 'user:Profil' product.author.id %}" style="text-transform: uppercase;">{{full_name}}</a></p>
            </div>
            {% if request.user.id != user.id%}
            <div class="px-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!" style="text-transform: uppercase;">Mesaj Gönder</a></p>
            </div>
            
            {% comment %} <div class="px-3 mb-2">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!">Favoriye Ekle</a></p>
            </div> {% endcomment %}
            {% endif %}
          </div>
        </div>
      </main>
    </div>
  </div>
</section>
<!-- content -->



<!-- detail message modal başlangıç-->
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start mt-3">
  <!--<a class="btn btn-outline-info btn-lg px-4" href="#!">Profili Düzenle</a>-->

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       {% if  request.user.is_authenticated %}
       <div class="alert alert-info  w-100 text-center" role="alert">
        <a  class="alert-link text-decoration-none"style="text-transform: uppercase;">{{full_name}}</a>
     
      </div>
       {% else %} 
       <h1 class="modal-title fs-5 " id="exampleModalLabel">
        <a href="{% url 'user:Login' %}" class="text-decoration-none">Mesajlaşmak için oturum açın...</a>
       </h1>
       {% endif %}
      
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

     </div>
     {% include 'adverts_details/detail_message_modal.html' %}

    <!-- modal mesaj başlangıç-->
    

<div class="modal-footer">
  {% comment %} <button type="submit" class="btn btn-primary">
    GİRİŞ YAP
  </button> {% endcomment %}

  {% comment %} <a href="{% url 'user:User_Info_Save'  %}" class="btn btn-warning d-block mt-1">Düzenle</a> {% endcomment %}


</div>
    <!-- modal mesaj bitiş-->
   </div>
 </div>
</div>

</div>
<!-- detail message modal bitiş-->




  <div class="row gx-4  ">
    <div class="col-lg-12 ">
      <div class="border rounded-2 px-3 py-2 bg-white shadow border-0">
          <!-- Pills navs -->
          <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
            <li class="nav-item d-flex" role="presentation">
              <a class="nav-link d-flex align-items-center " id="ex1-tab-1" data-mdb-toggle="pill" href="#ex1-pills-1" role="tab" aria-controls="ex1-pills-1" aria-selected="true">Ürün Açıklaması</a>
            </li>

          </ul>
          <!-- Pills navs -->
          <!-- Pills content -->
          <div class="tab-content" id="ex1-content">
            <div class="tab-pane fade show active" id="ex1-pills-1" role="tabpanel" aria-labelledby="ex1-tab-1">
              <p>
                {{product.comment}}
              </p>
            </div>

          </div>
          <!-- Pills content -->
      </div>


<!-- Footer -->

<!-- Footer -->



  </div>

{% include 'home/product.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script>
    // Özel JavaScript kodları buraya eklenebilir
  </script>

  {% endblock body %}

ucz/templates/adverts_details/phone_repair_details.html
{% extends 'base/base.html' %}

{% block body %}

  <div class="container mt-4">

<!-- content -->
<section class="py-5">
  <div class="container">
    <div class="row gx-5">
      <aside class="col-lg-6">
        <div class="border rounded-4 mb-3 d-flex justify-content-center bg-light shadow border-0">
          <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="{{ product.avatar.url }}">
            {% if product.avatar %}
            <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{ product.avatar.url }}" />
        {% else %}
            <p>Resim mevcut değil.</p>
        {% endif %}
          </a>
        </div>
      </aside>
      <main class="col-lg-6 ">
        <div class="ps-lg-3 bg-light shadow border-0">
          <h4 class="title text-dark pt-1 text-center">
            {{product.phone_brand}}-{{product.phone_model}}<br />
          </h4>
          <hr>
          <div class="row ">
            <dt class="col-3">Marka:</dt>
            <dd class="col-9">{{product.phone_brand}}</dd>
            <dt class="col-3">Model:</dt>
            <dd class="col-9">{{ product.phone_model}}</dd>
            <dt class="col-3">İl:</dt>
            <dd class="col-9">{{product.city}}</dd>
            <dt class="col-3">İlçe:</dt>
            <dd class="col-9">{{product.district}}</dd>
            <dt class="col-3">İlan Tarihi:</dt>
            <dd class="col-9">{{product.created_date|date:"d.m.Y"}}</dd>
            <dt class="col-3">Kategori:</dt>
            <dd class="col-3 badge bg-primary bg-gradient rounded-pill ">{{product.label}}</dd>
          </div>
          <hr>
          <div class="d-flex justify-content-center">
            <div class="mr-3">
              <p class="mb-3 mt-4 h5"></p>
              <p class="small text-muted-info mb-0" style="text-transform: uppercase;">İlan Sahibi:</p>
            </div>
            <div class="px-3 mb-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted mb-0"><a class="small text-decoration-none" href="{% url 'user:Profil' product.author.id %}" style="text-transform: uppercase;">{{full_name}}</a></p>
            </div>
            {% if request.user.id != user.id%}
            <div class="px-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!" style="text-transform: uppercase;">Mesaj Gönder</a></p>
            </div>
            
            {% comment %} <div class="px-3 mb-2">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted-info mb-0"><a class="small text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" href="#!">Favoriye Ekle</a></p>
            </div> {% endcomment %}
            {% if busines_s %}
            <div class="px-3">
              <p class="mb-1 h5 mt-4"></p>
              <p class="small text-muted mb-0"><a class="small text-decoration-none" href="{% url 'hospital:MobileRepair_Request_ID' product.id %} " style="text-transform: uppercase;">Tamir İsteği Gönder</a></p>
            </div>
            {% else %}
            {% endif %}


       
            
            {% endif %}
          </div>
        </div>
      </main>
    </div>
  </div>
</section>
<!-- content -->



<!-- detail message modal başlangıç-->
<div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start mt-3">
  <!--<a class="btn btn-outline-info btn-lg px-4" href="#!">Profili Düzenle</a>-->

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       {% if  request.user.is_authenticated %}
       <div class="alert alert-info  w-100 text-center" role="alert">
        <a  class="alert-link text-decoration-none"style="text-transform: uppercase;">{{full_name}}</a>
      
      </div>
       {% else %} 
       <h1 class="modal-title fs-5 " id="exampleModalLabel">
        <a href="{% url 'user:Login' %}" class="text-decoration-none">Mesajlaşmak için oturum açın...</a>
       </h1>
       {% endif %}
      
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

     </div>
     {% include 'adverts_details/detail_message_modal.html' %}

    <!-- modal mesaj başlangıç-->
    

<div class="modal-footer">
  {% comment %} <button type="submit" class="btn btn-primary">
    GİRİŞ YAP
  </button> {% endcomment %}

  {% comment %} <a href="{% url 'user:User_Info_Save'  %}" class="btn btn-warning d-block mt-1">Düzenle</a> {% endcomment %}


</div>
    <!-- modal mesaj bitiş-->
   </div>
 </div>
</div>

</div>
<!-- detail message modal bitiş-->





    <div class="row gx-4  ">
      <div class="col-lg-12 ">
        <div class="border rounded-2 px-3 py-2 bg-white shadow border-0">
          <!-- Pills navs -->
          <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
            <li class="nav-item d-flex" role="presentation">
              <a class="nav-link d-flex align-items-center " id="ex1-tab-1" data-mdb-toggle="pill" href="#ex1-pills-1" role="tab" aria-controls="ex1-pills-1" aria-selected="true">Ürün Açıklaması</a>
            </li>

          </ul>
          <!-- Pills navs -->
          <!-- Pills content -->
          <div class="tab-content" id="ex1-content">
            <div class="tab-pane fade show active" id="ex1-pills-1" role="tabpanel" aria-labelledby="ex1-tab-1">
              <p>
                {{product.comment}}
              </p>
            </div>

          </div>
          <!-- Pills content -->
        </div>
      </div>


<!-- Footer -->

<!-- Footer -->



  </div>

  {% include 'home/product.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script>
    // Özel JavaScript kodları buraya eklenebilir
  </script>

  {% endblock body %}