ucz/advert/urls.py
from django.urls import path
from .import views


app_name="advert"

urlpatterns = [


    path('phonesaless/<int:id>/',views.Phone_Sales, name='Phone_Sales'),
    path('phonerepairr/<int:id>/',views.Phone_Repair, name='Phone_Repair'),
    path('phonepartt/<int:id>/', views.Phone_Part, name='Phone_Part'),
    path('phoneaksesuarr/<int:id>/', views.Phone_Aksesuar, name='Phone_Aksesuar'),
    #---------------------DETAILS----------------------------------
    path('phonesales/<int:id>/', views.Phone_Sales_Details, name='Phone_Sales_Details'),
    path('phonerepair/<int:id>/', views.Phone_Repair_Details, name='Phone_Repair_Details'),
    path('phonepart/<int:id>/', views.Phone_Part_Details, name='Phone_Part_Details'),
    path('phoneaksesuar/<int:id>/',views.Phone_Aksesuar_Details, name='Phone_Aksesuar_Details'),


    
]

ucz/chat/urls.py
from django.urls import path
from .views import *

app_name="chat"

urlpatterns = [
    path('messages/', messages, name='messages'),
    path('messages/<int:receiver_id>/', messages, name='messages'),
]

ucz/home/urls.py
from django.urls import path
from .import views

app_name="home"
urlpatterns = [
    path('',views.index,name="index"),
    # path('about/',views.about,name="about"),
    # path('contact/',views.contact,name="contact"),
    # path('error/',views.error,name="error"),
    path('search', views.search_view, name='search'),
    path('contactform',views.Contact_Form, name='Contact_Form'),
    path('security',views.Security, name='Security'),
    path('conditions',views.Conditions, name='Conditions')

]

ucz/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls import handler404, handler500
from home.views import handle_not_found
from django.conf import settings #add this
from django.conf.urls.static import static #add this
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('user/', include("user.urls")),
    path('chat/', include("chat.urls")),
    path('advert/', include("advert.urls")),
    path('hospital/', include("hospital.urls")),
    # path('not-found/', handle_not_found, name='handle_not_found'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handle_not_found'

ucz/user/urls.py
from django.urls import path
from .import views

app_name="user"
urlpatterns = [
    path('login/',views.User_Login,name="Login"),
    path('register/',views.User_Register,name="Register"),
    path('profil/<int:id>/',views.User_Profil,name="Profil"),
    # path('User_Info_Save/',views.User_Info_Save,name="User_Info_Save"),
    path('User_Info_Update/<int:id>/',views.User_Info_Update,name="User_Info_Update"),


    path('logout/',views.logoutView,name="Logout"),

]

ucz/home/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
    name_surname=models.CharField(max_length=100,verbose_name="Ad-Soyad",null=True,blank=False)
    mail_address=models.CharField(max_length=50,verbose_name="Mail Adresi",null=True,blank=False)
    telephone=models.CharField(max_length=11,verbose_name="Telefon Numarası",null=True,blank=False)
    message=models.TextField(verbose_name="Mesajı",null=True,blank=False)
    created_date=models.DateTimeField(auto_now=True,verbose_name="Gönderilme Tarihi")

    def __str__(self):
        return  'Ad-Soyad={0}, Mesajı={1}, Gönderilme Tarihi{2}'.format(self.name_surname, self.message,self.created_date)

ucz/home/forms.py
from django import forms
from.models import *

class ContactModelForms(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

ucz/home/views.py
from django.contrib import messages
import random

from django.shortcuts import redirect, render
from django.db.models import Q
from advert.models import MobileRepair, PhoneSales, PhonePart, PhoneAksesuar
from django.db.models import Q

from user.models import BusinessStaff
from .forms import *
# Create your views here.
def handle_not_found(request, exception):
    return render(request, 'error_404_/error_404_.html')


def index(request):
    total_count_PhoneSales = PhoneSales.objects.filter(is_active=True).count()
    total_count_MobileRepair = MobileRepair.objects.filter(is_active=True).count()
    total_count_PhonePart = PhonePart.objects.filter(is_active=True).count()
    total_count_PhoneAksesuar = PhoneAksesuar.objects.filter(is_active=True).count()

    context = {}  # Declare an empty context dictionary

    if total_count_PhoneSales > 0 or total_count_MobileRepair > 0 or total_count_PhonePart > 0 or total_count_PhoneAksesuar > 0:
        # Diğer işlemler
        if total_count_PhoneAksesuar > 0:
            random_index_PhoneAksesuar = random.randint(0, total_count_PhoneAksesuar - 1)
            random_PhoneAksesuar = PhoneAksesuar.objects.all()[random_index_PhoneAksesuar]
            user_PhoneAksesuar = random_PhoneAksesuar.author
            full_name_PhoneAksesuar = user_PhoneAksesuar.get_full_name()
            context['random_PhoneAksesuar'] = random_PhoneAksesuar
            context['full_name_PhoneAksesuar'] = full_name_PhoneAksesuar

        if total_count_PhonePart > 0:
            random_index_PhonePart = random.randint(0, total_count_PhonePart - 1)
            random_PhonePart = PhonePart.objects.all()[random_index_PhonePart]
            user_PhonePart = random_PhonePart.author
            full_name_PhonePart = user_PhonePart.get_full_name()
            context['random_PhonePart'] = random_PhonePart
            context['full_name_PhonePart'] = full_name_PhonePart

        if total_count_MobileRepair > 0:
            random_index_MobileRepair = random.randint(0, total_count_MobileRepair - 1)
            random_MobileRepair = MobileRepair.objects.all()[random_index_MobileRepair]
            user_MobileRepair = random_MobileRepair.author
            full_name_MobileRepair = user_MobileRepair.get_full_name()
            context['random_MobileRepair'] = random_MobileRepair
            context['full_name_MobileRepair'] = full_name_MobileRepair

        if total_count_PhoneSales > 0:
            random_index_PhoneSales = random.randint(0, total_count_PhoneSales - 1)
            random_phonesale = PhoneSales.objects.all()[random_index_PhoneSales]
            user_PhoneSales = random_phonesale.author
            full_name_PhoneSales = user_PhoneSales.get_full_name()
            context['random_phonesale'] = random_phonesale
            context['full_name_PhoneSales'] = full_name_PhoneSales

    return render(request, "home/index.html", context)






def Security(request):

        return render(request,"home/security.html")


def Conditions(request):

    return render(request,"home/conditions.html")


def Contact_Form(request):
    if request.method == 'POST':
        form = ContactModelForms(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, "Mesaj bilgileriniz başarıyla gönderildi. En kısa zamanda dönüş sağlanılacaktır...")
            return redirect('home:Contact_Form')
        else:
            # Invalid form, display error message and pass the form back to the template
            messages.error(request, "Lütfen gerekli tüm alanları doldurun.")
    
    return render(request, "home/contactform.html")

import re

# def normalize_query(query):
#     replacements = {
#         'ı': '[ıI]',
#         'İ': '[iİ]',
#         'ş': '[şŞ]',
#         'Ş': '[şŞ]',
#         'ğ': '[ğĞ]',
#         'Ğ': '[ğĞ]',
#         'ü': '[üÜ]',
#         'Ü': '[üÜ]',
#         'ö': '[öÖ]',
#         'Ö': '[öÖ]',
#         'ç': '[çÇ]',
#         'Ç': '[çÇ]',
#     }

#     for char, replacement in replacements.items():
#         query = re.sub(char, replacement, query)

#     return query

def normalize_query(query):
    replacements = {
        'ı': '[ıI]',
        'İ': '[iİ]',
        'ş': '[şŞ]',
        'Ş': '[şŞ]',
        'ğ': '[ğĞ]',
        'Ğ': '[ğĞ]',
        'ü': '[üÜ]',
        'Ü': '[üÜ]',
        'ö': '[öÖ]',
        'Ö': '[öÖ]',
        'ç': '[çÇ]',
        'Ç': '[çÇ]',
    }

    for char, replacement in replacements.items():
        query = re.sub(char, replacement, query)

    return query

def search_view(request):
    query = request.GET.get('query')
    if query == "":
        return redirect('/')

    query = normalize_query(query)

    mobile_repairs = search_mobile_repair(query)
    phone_sales = search_phone_sales(query)
    phone_parts = search_phone_part(query)
    phone_aksesuars = search_phone_aksesuar(query)
    business_staff = search_business_staff(query)

    return render(request, 'home/search.html', {
        'mobile_repairs': mobile_repairs,
        'phone_sales': phone_sales,
        'phone_parts': phone_parts,
        'phone_aksesuars': phone_aksesuars,
        'business_staff': business_staff,
    })

def search_mobile_repair(query):
    normalized_query = normalize_query(query)
    results = MobileRepair.objects.filter(
        Q(phone_brand__iregex=normalized_query) |
        Q(phone_model__iregex=normalized_query) |
        Q(city__iregex=normalized_query) |
        Q(label__iregex=normalized_query) |
        Q(district__iregex=normalized_query) |
        Q(author__first_name__iregex=normalized_query) |
        Q(author__last_name__iregex=normalized_query) |
        Q(comment__iregex=normalized_query)
    ).filter(is_active=True)

    # Add author's full name to the results
    for repair in results:
        repair.author_full_name = f"{repair.author.first_name} {repair.author.last_name}"

    return results

def search_phone_sales(query):
    normalized_query = normalize_query(query)
    results = PhoneSales.objects.filter(
        Q(phone_brand__iregex=normalized_query) |
        Q(phone_model__iregex=normalized_query) |
        Q(city__iregex=normalized_query) |
        Q(label__iregex=normalized_query) |
        Q(district__iregex=normalized_query) |
        Q(author__first_name__iregex=normalized_query) |
        Q(author__last_name__iregex=normalized_query) |
        Q(comment__iregex=normalized_query)
    ).filter(is_active=True)

    # Add author's full name to the results
    for sale in results:
        sale.author_full_name = f"{sale.author.first_name} {sale.author.last_name}"

    return results

def search_phone_part(query):
    normalized_query = normalize_query(query)
    results = PhonePart.objects.filter(
        Q(part_name__iregex=normalized_query) |
        Q(city__iregex=normalized_query) |
        Q(label__iregex=normalized_query) |
        Q(author__first_name__iregex=normalized_query) |
        Q(author__last_name__iregex=normalized_query) |
        Q(district__iregex=normalized_query)
    ).filter(is_active=True)

    # Add author's full name to the results
    for part in results:
        part.author_full_name = f"{part.author.first_name} {part.author.last_name}"

    return results

def search_phone_aksesuar(query):
    normalized_query = normalize_query(query)
    results = PhoneAksesuar.objects.filter(
        Q(aksesuar_name__iregex=normalized_query) |
        Q(city__iregex=normalized_query) |
        Q(district__iregex=normalized_query) |
        Q(label__iregex=normalized_query) |
        Q(comment__iregex=normalized_query) |
        Q(author__first_name__iregex=normalized_query) |
        Q(author__last_name__iregex=normalized_query)
    ).filter(is_active=True)

    # Add author's full name to the results
    for aksesuar in results:
        aksesuar.author_full_name = f"{aksesuar.author.first_name} {aksesuar.author.last_name}"

    return results

def search_business_staff(query):
    normalized_query = normalize_query(query)
    results = BusinessStaff.objects.filter(
        Q(author__username__iregex=normalized_query) |
        Q(author__first_name__iregex=normalized_query) |
        Q(author__last_name__iregex=normalized_query) |
        Q(address__iregex=normalized_query)
    ).filter(is_active=True)

    # Add full name and avatar to the results
    for staff_member in results:
        staff_member.author_name = f"{staff_member.author.first_name} {staff_member.author.last_name}"
        staff_member.avatar_url = staff_member.author.avatar.url if hasattr(staff_member.author, 'avatar') else None

    return results

ucz/templates/home/conditions.html
{% extends 'base/base.html' %}
{% block body %}
<hr style="margin-top:45px;">

<header class=" py-5 container shadow-sm border-0 rounded ">
    <div class="px-md-5">
        <h1 class="text-center mb-5">Şartlar ve Koşullar</h1>

        <h2>Kabul Edilme</h2>
      
        <p>Web sitemizi ziyaret ederek veya hizmetlerimizi kullanarak, aşağıdaki şartları ve koşulları kabul etmiş sayılırsınız. Bu şartlar ve koşulları kabul etmiyorsanız, web sitemizi kullanmayınız.</p>
      
        <h2>Fikri Mülkiyet Hakları</h2>
      
        <p>Web sitemizdeki tüm içerik, telif hakları ve diğer fikri mülkiyet haklarıyla korunmaktadır. İzinsiz olarak kopyalanması, dağıtılması veya kullanılması yasaktır.</p>
      
        <h2>Hizmetlerin Kullanımı</h2>
      
        <p>Hizmetlerimizi yasal amaçlarla ve ilgili yasaları ihlal etmeden kullanmanız gerekmektedir. Hizmetlerimizin kötüye kullanılması, başkalarının haklarını ihlal etmesi veya yasa dışı faaliyetlerde bulunulması yasaktır.</p>
      
        <h2>İptal ve Geri Ödeme</h2>
      
        <p>Ücretli hizmetlerimizle ilgili iptal ve geri ödeme politikaları ayrı bir sözleşmeye tabidir. Lütfen ilgili sözleşmeyi inceleyiniz.</p>
      
        <h2>Bağlantılar</h2>
      
        <p>Web sitemiz, diğer web sitelerine bağlantılar içerebilir. Bu bağlantılar yalnızca referans amaçlıdır. Bağlantı verilen web sitelerinin içerik ve politikalarından sorumlu değiliz.</p>
      
        <h2>Sorumluluk Reddi</h2>
      
        <p>Hizmetlerimizin kullanımından kaynaklanan herhangi bir zarar veya kayıp için sorumluluk kabul etmemekteyiz. Hizmetlerimizi kendi riskinizde kullanmanız gerekmektedir.</p>
      
        <h2>Gizlilik Politikası</h2>
      
        <p>Web sitemizin gizlilik politikasını okumak için lütfen <a href="{% url 'home:Security' %}" class="text-decoration-none">buraya</a> tıklayınız.</p>
      
        <h2>Değişiklikler</h2>
      
        <p>Şartlar ve koşullarımızı zaman zaman güncelleyebiliriz. Bu sayfayı düzenli olarak kontrol etmenizi öneririz.</p>
      
        <h2>İletişim</h2>
      
        <p>Şartlar ve koşullarımızla ilgili herhangi bir sorunuz varsa, lütfen bize <a href="{% url 'home:Contact_Form' %}" class="text-decoration-none">iletişim</a>  kısmından ulaşın.</p>
    </div>
</header>

{% endblock body %}

ucz/templates/home/search.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}
<!-- home/search.html -->
<!-- home/search.html -->



{% comment %} <section class="py-5 mt-3">
  <div class="container px-5 shadow border-0">
    <div class="row gx-5">
      {% if business_staff %}
      <h2 class="fw-bolder fs-5 mb-4 text-center pt-3 text-primary">Kişiler veya İşletmeler</h2>
      {% for staff_member in business_staff %}
      <div class="col-sm-3 mb-3" style="">
        <div class="card text-white" style="background: rgb(238,174,202);
        background: radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,187,233,1) 100%);">
          <div class="card-body">
            <h5 class="card-title text-center">
              <a href="{% url 'user:Profil' staff_member.author.id %}" class="text-white text-decoration-none" style="text-transform: uppercase;">{{ staff_member.author_name|truncatechars:15 }}</a>
            </h5>
            <p class="card-text">Adres:{{ staff_member.address|truncatechars:18 }}</p>
            <a href="{% url 'user:Profil' staff_member.author.id %}" class="btn btn-warning d-block text-white">Görüntüle</a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</section> {% endcomment %}
<hr>
<section class="container py-3 mt-5 shadow border-0 rounded">
  <div class="container">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      {% if business_staff %}
      <h2 class="fw-bold fs-4 mb-4 text-center text-primary">Kişiler veya İşletmeler</h2>
      {% for staff_member in business_staff %}
      <div class="col-md-3 mb-4">
        <div class="card bg-light border-0 rounded-3 shadow">
          <div class="card-body text-center">
            <div class="profile-picture">
              {% comment %} <img src="{{ staff_member.avatar }}" alt="{{ staff_member.author_name }}" class="rounded-circle mb-3"> {% endcomment %}
              <i class="fas fa-user-circle"></i> <!-- Replace with appropriate font icon -->
            </div>
            {% if staff_member.is_staff %}
            <p class="card-text mb-3"><i class="bi bi-shop"></i> İşletme sahibi</p> <!-- Replace with appropriate font icon -->
          {% else %}
            <p class="card-text mb-3"><i class="bi bi-person"></i> Kişisel hesap</p> <!-- Replace with appropriate font icon -->
          {% endif %}
            <h5 class="card-title text-uppercase mb-2">{{ staff_member.author_name|truncatechars:15 }}</h5>
            <p class="card-text mb-3">Adres: {{ staff_member.address|truncatechars:18 }}</p>
            <a href="{% url 'user:Profil' staff_member.author.id %}" class="btn btn-primary btn-block w-100"><i class="bi bi-arrow-right"></i></a>
            <div class="social-media-links mt-2 " style=" display: flex;justify-content: center;align-items: center;height:20px">
              {% if staff_member.social_media_facebook %}
              <a href="{{staff_member.social_media_facebook}}"  target="_blank" class="social-link" style="display: inline-block;margin-right: 1rem;"><i class="bi bi-facebook"></i></a> <!-- Replace with appropriate font icon and link -->
              {% endif %}
              {% if staff_member.social_media_twitter %}
              <a href="{{staff_member.social_media_twitter}}"  target="_blank" class="social-link" style="display: inline-block;margin-right: 1rem;"><i class="bi bi-twitter"></i></a> <!-- Replace with appropriate font icon and link -->
              {% endif %}
              {% if staff_member.social_media_instagram %}
              <a href="{{staff_member.social_media_instagram}}"  target="_blank" class="social-link" style="display: inline-block;margin-right: 1rem;"><i class="bi bi-instagram"></i></a> <!-- Replace with appropriate font icon and link -->
              {% endif %}
              {% if staff_member.social_media_tiktok %}
              <a href="{{staff_member.social_media_tiktok}}"  target="_blank" class="social-link" style="display: inline-block;margin-right: 1rem;"><i class="bi bi-tiktok"></i></a> <!-- Replace with appropriate font icon and link -->
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="col-12 text-center">
        <p class="fs-5">Üye bulunamadı.</p>
      </div>
      {% endif %}
    </div>
  </div>
</section>


<section class="py-3 ">
    <div class="container px-5 shadow border-0 rounded">
        <h2 class="fw-bold mb-1 fs-4 mb-4 text-center text-primary ">Tamir/Satılık Ürünler/Telefon Parçaları/Aksesuar</h2>
        <div class="row gx-5">
<!-- cardlar başlangıç-->

{% if mobile_repairs %}
{% for phone_repair in mobile_repairs %}
<div class="col-lg-4 mb-5">
    <div class="card h-100 shadow border-0">

      {% if phone_repair.avatar %}
      <img class="card-img-top" src="{{ phone_repair.avatar.url }}" style="height: 250px;" alt="..." />
      {% else %}
  <p>ÜRün Resmi Bulunmamaktadır</p>
    {% endif %}
        <div class="card-body p-4">
            <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{ phone_repair.label}}</div>
            <a class="text-decoration-none link-dark stretched-link" href="{% url 'advert:Phone_Repair_Details' phone_repair.id %}"><div class="h5 card-title mb-3">{{ phone_repair.phone_brand }}-{{ phone_repair.phone_model }}</div></a>
            <p class="card-text mb-0">{{ phone_repair.comment |truncatechars:205}}</p>
        </div>
        <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
            <div class="d-flex align-items-end justify-content-between">
                <div class="d-flex align-items-center">
                    {% comment %} <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." /> {% endcomment %}
                    <div class="small align-items-start">
                      <div class="fw-bold" style="text-transform: uppercase;">{{ phone_repair.author_full_name |truncatechars:8}}</div>
                      <div class="text-muted">{{ phone_repair.created_date|date:"d.m.Y"}}</div>
                    </div>
                    
                    <div class="small align-items-end" style="margin-left:135px">
                      <div class="fw-bold">{{ phone_repair.city|truncatechars:12 }}</div>
                      <div class="text-muted">{{ phone_repair.district|truncatechars:12 }}</div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% empty %}
{% comment %} <p>Kullanıcı hiç telefon tamir ilanı Oluşturmamış.</p> {% endcomment %}
{% endfor %}
    {% endif %}
    {% if phone_sales %}


    {% for phone_sale in phone_sales %}
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">

          {% if phone_sale.avatar %}
          <img class="card-img-top" src="{{ phone_sale.avatar.url }}" style="height: 250px;" alt="..." />
          {% else %}
      <p>ÜRün Resmi Bulunmamaktadır</p>
        {% endif %}
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{ phone_sale.label}}</div>
               <div class="badge bg-danger bg-gradient rounded-pill mb-2 " >{{ phone_sale.price}}&nbsp;TL</div>

                <a class="text-decoration-none link-dark stretched-link" href="{% url 'advert:Phone_Sales_Details' phone_sale.id %}"><div class="h5 card-title mb-3">{{ phone_sale.phone_brand }}-{{ phone_sale.phone_model }}</div></a>
                <p class="card-text mb-0">{{ phone_sale.comment |truncatechars:205}}</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        {% comment %} <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." /> {% endcomment %}
                        <div class="small align-items-start">
                          <div class="fw-bold" style="text-transform: uppercase;">{{ phone_sale.author_full_name |truncatechars:8}}</div>
                          <div class="text-muted">{{ phone_sale.created_date|date:"d.m.Y"}}</div>
                        </div>
                        
                        <div class="small align-items-end" style="margin-left:135px">
                          <div class="fw-bold">{{ phone_sale.city|truncatechars:12 }}</div>
                          <div class="text-muted">{{ phone_sale.district|truncatechars:12 }}</div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    {% comment %} <p>Kullanıcı hiç telefon ilanı Oluşturmamış.</p> {% endcomment %}
{% endfor %}
    {% endif %}
    {% if phone_parts %}
    {% for phone_part in phone_parts %}
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">

          {% if phone_part.avatar %}
          <img class="card-img-top" src="{{ phone_part.avatar.url }}" style="height: 250px;" alt="..." />
          {% else %}
      <p>ÜRün Resmi Bulunmamaktadır</p>
        {% endif %}
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{ phone_part.label}}</div>
                <div class="badge bg-danger bg-gradient rounded-pill mb-2 " >{{ phone_part.price}}&nbsp;TL</div>
                <a class="text-decoration-none link-dark stretched-link" href="{% url 'advert:Phone_Part_Details' phone_part.id %}"><div class="h5 card-title mb-3">{{ phone_part.part_name }}</div></a>
                <p class="card-text mb-0">{{ phone_part.comment |truncatechars:205}}</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        {% comment %} <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." /> {% endcomment %}
                        <div class="small align-items-start">
                          <div class="fw-bold" style="text-transform: uppercase;">{{ phone_part.author_full_name |truncatechars:8}}</div>
                          <div class="text-muted">{{ phone_part.created_date|date:"d.m.Y"}}</div>
                        </div>
                        
                        <div class="small align-items-end" style="margin-left:135px">
                          <div class="fw-bold">{{ phone_part.city|truncatechars:12 }}</div>
                          <div class="text-muted">{{ phone_part.district |truncatechars:12}}</div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    {% comment %} <p>Kullanıcı hiç telefon tamir ilanı Oluşturmamış.</p> {% endcomment %}
{% endfor %}
    {% endif %}
    {% if phone_aksesuars %}
    {% for phone_aksesuar in phone_aksesuars %}
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
    
          {% if phone_aksesuar.avatar %}
          <img class="card-img-top" src="{{ phone_aksesuar.avatar.url }}" style="height: 250px;" alt="..." />
          {% else %}
      <p>ÜRün Resmi Bulunmamaktadır</p>
        {% endif %}
            <div class="card-body p-4">
                <div class="badge bg-primary bg-gradient rounded-pill mb-2">{{ phone_aksesuar.label}}</div>
                <div class="badge bg-danger bg-gradient rounded-pill mb-2 " >{{ phone_aksesuar.price}}&nbsp;TL</div>
                <a class="text-decoration-none link-dark stretched-link" href="{% url  'advert:Phone_Aksesuar_Details' phone_aksesuar.id %}"><div class="h5 card-title mb-3">{{ phone_aksesuar.aksesuar_name }}</div></a>
                <p class="card-text mb-0">{{ phone_aksesuar.comment |truncatechars:205}}</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        {% comment %} <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." /> {% endcomment %}
                        <div class="small align-items-start">
                          <div class="fw-bold" style="text-transform: uppercase;">{{ phone_aksesuar.author_full_name |truncatechars:13}}</div>
                          <div class="text-muted">{{ phone_aksesuar.created_date|date:"d.m.Y"}}</div>
                        </div>
                        
                        <div class="small align-items-end" style="margin-left:135px">
                          <div class="fw-bold">{{ phone_aksesuar.city |truncatechars:12}}</div>
                          <div class="text-muted">{{ phone_aksesuar.district|truncatechars:12 }}</div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    {% comment %} <p>Kullanıcı hiç telefon tamir ilanı Oluşturmamış.</p> {% endcomment %}
    {% endfor %}
    {% endif %}


</section>
   <!-- card bitiş--> 
    {% endblock body %}